In [1]:
import torch
import torch.nn as nn
import numpy as np


torch.manual_seed(0)
np.random.seed(0)

In [2]:
h1 = nn.Linear(2, 20)
h2 = nn.Linear(20, 20)
h3 = nn.Linear(20, 1)

inp = torch.rand([5,2])

test = h1(inp)
test

tensor([[ 3.1739e-01, -1.2493e+00,  2.9739e-02, -2.5135e-01, -4.2400e-01,
         -6.5107e-01, -4.8135e-01,  1.8572e-01,  2.4321e-01, -6.6537e-01,
          1.1119e+00,  9.7604e-01,  2.3962e-01,  1.4910e-01, -3.9817e-02,
         -1.9280e-01, -5.0335e-01, -1.4665e+00, -3.8581e-01,  1.6099e-01],
        [ 3.8319e-01, -1.3062e+00,  7.7922e-02, -1.5374e-01, -3.8813e-01,
         -6.6296e-01, -5.2393e-01,  2.0676e-01,  3.0063e-01, -6.9137e-01,
          1.1988e+00,  1.0757e+00,  2.5900e-01, -4.7389e-04, -4.5494e-02,
         -7.1677e-02, -5.3358e-01, -1.5529e+00, -2.5745e-01,  2.0228e-01],
        [ 2.8552e-01, -8.3904e-01,  1.8160e-01, -2.9460e-01, -4.0230e-01,
         -5.0524e-01, -1.7678e-02,  3.6463e-01,  2.9972e-02, -3.3860e-01,
          8.9774e-01,  1.0175e+00,  3.0359e-01, -1.8843e-01,  2.5372e-01,
         -7.7955e-02, -1.8804e-01, -1.0978e+00, -1.8536e-01, -6.7075e-02],
        [ 1.6708e-01, -9.5590e-01, -5.4745e-03, -4.7260e-01, -4.8924e-01,
         -5.6407e-01, -1.9481e-01, 

In [3]:
l = list(h1.parameters())

print(l[0].size())
w1 = l[0].clone().detach().numpy()
b = l[1].clone().detach().numpy()


torch.Size([20, 2])


In [29]:
np.matmul(inp.numpy(), w1.T) + b

array([[ 3.17386031e-01, -1.24933958e+00,  2.97385380e-02,
        -2.51349360e-01, -4.23996061e-01, -6.51068330e-01,
        -4.81352091e-01,  1.85717136e-01,  2.43210852e-01,
        -6.65371776e-01,  1.11194634e+00,  9.76037383e-01,
         2.39618167e-01,  1.49097711e-01, -3.98166776e-02,
        -1.92802310e-01, -5.03348470e-01, -1.46651411e+00,
        -3.85808229e-01,  1.60986602e-01],
       [ 3.83189559e-01, -1.30621028e+00,  7.79215917e-02,
        -1.53737962e-01, -3.88127714e-01, -6.62955821e-01,
        -5.23925245e-01,  2.06764698e-01,  3.00630331e-01,
        -6.91368937e-01,  1.19878244e+00,  1.07566106e+00,
         2.58999944e-01, -4.73894179e-04, -4.54943180e-02,
        -7.16765225e-02, -5.33575416e-01, -1.55286908e+00,
        -2.57445753e-01,  2.02281356e-01],
       [ 2.85519451e-01, -8.39039624e-01,  1.81595311e-01,
        -2.94601709e-01, -4.02300298e-01, -5.05238771e-01,
        -1.76784098e-02,  3.64629567e-01,  2.99723446e-02,
        -3.38598371e-01,  8.9

In [178]:
# Layers have size (out, in)

b = None
for i in range(100):
    h1 = np.random.normal(loc=-0.01/10, scale=0.000000001, size=(20,2))
    h1[:,1] -= h1[:,1] + np.random.normal(loc=0,scale=0.1, size=(20,))
    h2 = np.random.normal(loc=1, scale=1, size=(20,20))
    h3 = np.random.normal(loc=1, scale=1, size=(1,20))

    o1 = np.matmul(inp.numpy(), h1.T)
    o2 = np.matmul(o1, h2.T)
    o3 = np.matmul(o2, h3.T).flatten()

    if b is None:
        b = (o3 - inp[:,0].numpy().flatten()*-0.01)*(o3 - inp[:,0].numpy()*-0.01)
    else:
        b += (o3 - inp[:,0].numpy().flatten()*-0.01)

print(b/100)

[-0.4052481  -0.39915    -0.17006285 -0.30969043 -0.29643335]


In [276]:
b.shape

(25,)

In [5]:
inp[:,0]*-0.01

tensor([-0.0085, -0.0080, -0.0023, -0.0070, -0.0067])